steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=gitops-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:aifimmunology/cell-hashing-pipeline
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args: [ "-c", "docker build -t us.gcr.io/$PROJECT_ID/cellhashing:v${_HISE_VERSION}_${_ENV}3 ." ]
  env: ['PROJECT_ROOT=github.com/aifimmunology/cell-hashing-pipeline']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args: [ "-c", "docker push us.gcr.io/$PROJECT_ID/cellhashing:v${_HISE_VERSION}_${_ENV}3"]
  env: ['PROJECT_ROOT=github.com/aifimmunology/cell-hashing-pipeline']
timeout: 1800s
